version: '3.8'

services:
  # Mysql
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  # Java
  backend:
    image: openjdk:17
    container_name: java_container
    environment:
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      aws_session_token: 
    build:
      context: ./dockerfiles/backend
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - db
  # Node.js
  frontend:
    image: node:18
    container_name: node_container
    build:
      context: ./dockerfiles/frontend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - db

volumes:
  db_data:    